# This is basic workflow to help you get started with action
name: CI 
# Control when action will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# Allow you to run this workflow manually from action tab
  workflow_dispatch:
# A workflow run is madeup of one or more jobs that can run sequentially or parallel
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-list script
        run: echo Hello CI CD

      - name: Run a multi-line script
        run: |
            echo add other action to build
            echo test, and deploy your project
